### ISSUE TITLE
部署hdfs 时报zkfc部署失败

### ISSUE THREAD

**Issue by lishijiang** [DTStack/chengying-schema#2]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/28666812/180609071-6d413140-1730-49a1-b261-4d2bd5bc4c5d.png">

**Comment by lishijiang** [comment]
> <img alt="image" width="763" src="https://user-images.githubusercontent.com/28666812/180609071-6d413140-1730-49a1-b261-4d2bd5bc4c5d.png">

日志报：
Exception in thread "main" org.apache.hadoop.HadoopIllegalArgumentException: Could not get the namenode ID of this node. You may run zkfc on the node other than namenode.
        at org.apache.hadoop.hdfs.tools.DFSZKFailoverController.create(DFSZKFailoverController.java:138)
        at org.apache.hadoop.hdfs.tools.DFSZKFailoverController.main(DFSZKFailoverController.java:189)
问题已经解决：
发现是zkfc没有跟namenode部署到同一个节点上

**Comment by yqhy0718** [comment]
hdfs_zkfc和namenode需要部署在相同节点，详见角色分布图：
![image](https://user-images.githubusercontent.com/77104177/182324108-da4ae74b-6329-49af-a08e-2583f3fdab81.png)

**Comment by yqhy0718** [comment]
hdfs_zkfc和namenode需要部署在相同节点，详见角色分布图：
![image](https://user-images.githubusercontent.com/77104177/182324401-f41b91ae-198e-46a9-b2de-5b3d48f8460e.png)
